#######################################
# PHP application Docker container
#######################################
app:
  build: .
  dockerfile: Dockerfile.development
  #environment:
    #PHP_XDEBUG_ENABLED: 1
    # replace <ip address> with the ip address of your host machine. See Xdebug section in etc/php/development.ini
    #XDEBUG_CONFIG: remote_host=<ip address> remote_log=/tmp/debug/xdebug.log remote_connect_back=off
  links:
    - mysql
    #- postgres
    #- mail
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
    #- ftp
  ports:
    - "8000:80"
    - "8443:443"
    - "10022:22"
  expose:
    - "9000"
  volumes:
    - ./app/:/app/
    - ./tmp/debug/:/tmp/debug/
    - ./:/docker/
  volumes_from:
    - storage
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - etc/environment.yml
    - etc/environment.development.yml

#######################################
# MySQL server
#######################################
mysql:
  build: docker/mysql
  dockerfile: MySQL-5.5
  #dockerfile: MySQL-5.6
  #dockerfile: MySQL-5.7
  #dockerfile: MariaDB-5.5
  #dockerfile: MariaDB-10
  #dockerfile: Percona-5.5
  #dockerfile: Percona-5.6
  ports:
    - 13306:3306
  volumes_from:
    - storage
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - etc/environment.yml
    - etc/environment.development.yml

#######################################
# PostgreSQL server
#######################################
#postgres:
#  build: docker/postgres/
#  ports:
#    - 15432:5432
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.development.yml

#######################################
# Solr server
#######################################
#solr:
#  build: docker/solr/
#  ports:
#    - 18983:8983
#  volumes_from:
#    - storage
#  environment:
#    - SOLR_STORAGE=/storage/solr/server-master/
#  env_file:
#    - etc/environment.yml
#    - etc/environment.development.yml

#######################################
# Elasticsearch
#######################################
#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.development.yml

#######################################
# Redis
#######################################
redis:
  build: docker/redis/
  volumes_from:
    - storage
  env_file:
    - etc/environment.yml
    - etc/environment.development.yml

#######################################
# Memcached
#######################################
#memcached:
#  build: docker/memcached/
#  volumes_from:
#    - storage
#  env_file:
#    - etc/environment.yml
#    - etc/environment.development.yml

#######################################
# Mailcatcher
#######################################
#mail:
#  build: docker/mail/
#  ports:
#    - 1080:1080
#  env_file:
#    - etc/environment.yml
#    - etc/environment.development.yml

#######################################
# FTP (vsftpd)
#######################################
#ftp:
#  build: docker/vsftpd/
#  volumes_from:
#    - storage
#  volumes:
#    - ./:/application/
#  env_file:
#    - etc/environment.yml
#    - etc/environment.development.yml

#######################################
# Storage
#######################################
storage:
  build: docker/storage/
  volumes:
    - /storage
